services:
    laravel.test:
        build:
            context: './backend/docker/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
                MYSQL_CLIENT: mariadb-client
        image: 'sail-8.4/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8081}:80'
            # - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - './backend:/var/www/html'
        networks:
            - docker_101
        depends_on:
            - mariadb
    mariadb:
        image: 'mariadb:11'
        ports:
            - '${FORWARD_DB_PORT:-3310}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'backend'
            MYSQL_USER: 'sail'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - './backend/sail-mariadb:/var/lib/mysql'
            - './backend/vendor/laravel/sail/database/mariadb/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - docker_101
        healthcheck:
            test:
                - CMD
                - healthcheck.sh
                - '--connect'
                - '--innodb_initialized'
            retries: 3
            timeout: 5s
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        environment:
            VUE_APP_USER_NAME: ${USER}
            # VUE_APP_BACKEND_URL: 'http://localhost:8081'
            VUE_APP_BACKEND_URL: 'https://cremorne.ngrok.io'
        ports:
            - "5173:5173"
            - "8080:8080"
        volumes:
            - ./frontend:/app
        command: npm run serve
networks:
    docker_101:
        driver: bridge
volumes:
    sail-mariadb:
        driver: local
